services:
  wireguard-tunnel:
    image: linuxserver/wireguard:latest
    container_name: wireguard-tunnel
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - SERVERURL=${TUNNEL_SERVER_URL}
      - SERVERPORT=51821
      - PEERS=${TUNNEL_PEERS}
      - PEERDNS=10.14.14.1
      - INTERNAL_SUBNET=10.14.14.0/24
      - ALLOWEDIPS=10.14.14.0/24
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - "51821:51821/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      - wireguard-net
